# ACI playbook - Sample - Tasks
---
- name: Couple of ACI Tasks
  hosts: aci
  connection: local
  gather_facts: no

  vars:
    aci_login: &aci_login
      host: "{{ ansible_host }}"
      username: "{{ aci_username }}"
      password: "{{ aci_password }}"
      validate_certs: "{{ aci_validate_certs }}"

  vars_files:
    - dev_tn_variables.yaml

  tasks:
    - name: Add Application Profile
      aci_ap:
        <<: *aci_login
        tenant: "{{ tenant_name }}"
        ap: "{{ app_name }}"
        state: present

    - name: Add EPG
      aci_epg:
        <<: *aci_login
        tenant: "{{ tenant_name }}"
        ap: "{{ app_name }}"
        epg: "{{ item.name }}"
        bd: "{{ item.bd }}"
        preferred_group: "{{ item.prefGroup }}"
        state: present
      loop: "{{ epgs }}"

    - name: Add contracts for app demo
      aci_epg_to_contract:
        <<: *aci_login
        tenant: "{{ tenant_name }}"
        ap: "{{ app_name }}"
        epg: "{{ item.0.name }}"
        contract: "{{ item.1.contract }}"
        contract_type: "{{ item.1.type }}"
        state: present
      loop: "{{ epgs | subelements('contracts') }}"
      loop_control:
        pause: 1

    - name: Add contracts
      aci_contract:
        <<: *aci_login
        tenant: "{{ tenant_name }}"
        contract: "{{ item.name }}"
        description: "{{ item.descr }}"
        scope: "{{ item.scope }}"
        state: present
      loop: "{{ contracts }}"

    - name: Add contract subjects
      aci_contract_subject:
        <<: *aci_login
        tenant: "{{ tenant_name }}"
        contract: "{{ item.name }}"
        subject: "{{ item.subject }}"
        reverse_filter: "{{ item.reverse_filter }}"
        state: present
      loop: "{{ contracts }}"

    - name: Bind filters to contract subjects
      aci_contract_subject_to_filter:
        <<: *aci_login
        tenant: "{{ tenant_name }}"
        contract: "{{ item.0.name }}"
        subject: "{{ item.0.subject }}"
        filter: "{{ item.1 }}"
        log: log
        state: present
      loop: "{{ contracts | subelements('filters') }}"

    - name: Add Physical Domain to EPG
      aci_epg_to_domain:
        <<: *aci_login
        tenant: "{{ tenant_name }}"
        ap: "{{ app_name }}"
        epg: "{{ item.name }}"
        domain: "UCS_Chassis"
        domain_type: phys
        state: present
      loop: "{{ epgs }}"
      loop_control:
        pause: 2
        
    - name: Add Port to EPG
      aci_static_binding_to_epg:
        <<: *aci_login
        tenant: "{{ tenant_name }}"
        ap: "{{ app_name }}"
        epg: "{{ item.name }}"
        encap_id: 222
        deploy_immediacy: lazy
        interface_mode: untagged
        interface_type: switch_port
        pod_id: 1
        leafs: 101
        interface: '1/7'
        state: present
      loop: "{{ epgs }}"
      loop_control:
        pause: 2

